# Generated by Django 5.1.3 on 2024-11-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursegroup', '0001_initial'),
        ('offered_program', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('cnic_no', models.CharField(default='Not Provided', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='std_photos/')),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile_no', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('father_cnic', models.CharField(max_length=20, null=True)),
                ('father_mobile_no', models.CharField(max_length=15, null=True)),
                ('father_occupation', models.CharField(max_length=255, null=True)),
                ('guardian_name', models.CharField(max_length=255, null=True)),
                ('guardian_cnic', models.CharField(max_length=20, null=True)),
                ('guardian_contact_no', models.CharField(max_length=15, null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('postal_address', models.TextField(null=True)),
                ('nationality', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('religion', models.CharField(max_length=50, null=True)),
                ('hafiz_e_quran', models.BooleanField(default=False, null=True)),
                ('blood_group', models.CharField(default='Unknown', max_length=10)),
                ('marital_status', models.CharField(max_length=10, null=True)),
                ('disability_status', models.BooleanField(default=False, null=True)),
                ('related_to_worker', models.BooleanField(default=False)),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_department', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('user_id', models.CharField(default=0, max_length=50)),
                ('verifiy_status', models.CharField(max_length=50, null=True)),
                ('merit_lit_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('prospectus_fee', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('course_groups', models.ManyToManyField(to='coursegroup.coursegroup')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offered_program.programs')),
            ],
        ),
    ]
