# Generated by Django 5.1.3 on 2024-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_district_province_remove_student_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hafiz_doc',
            field=models.FileField(blank=True, null=True, upload_to='hafiz_doc/'),
        ),
    ]
