# Generated by Django 5.1.3 on 2024-11-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_hafiz_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='worker_department',
        ),
    ]
