# Generated by Django 5.1.3 on 2024-11-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyrecord',
            name='image',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='teacher_images/'),
        ),
    ]
