# Generated by Django 5.1.3 on 2024-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_facultyrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyrecord',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='teacher_images/'),
        ),
    ]
