# Generated by Django 5.1.3 on 2024-11-12 04:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', tinymce.models.HTMLField()),
                ('slider_image', models.FileField(default=None, max_length=250, null=True, upload_to='slider_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
