# Generated by Django 5.1.3 on 2024-11-12 04:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colgevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colgevent.colgevent')),
            ],
        ),
    ]
