# Generated by Django 5.1.3 on 2024-11-12 04:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('admission_detail', models.CharField(max_length=255)),
                ('note', tinymce.models.HTMLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=50)),
            ],
        ),
    ]
