# Generated by Django 5.1.3 on 2024-11-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='AcademicRecord',
        ),
    ]
