# Generated by Django 5.1.3 on 2024-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColgLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colg_logo', models.FileField(default=None, max_length=2500, null=True, upload_to='logo/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
