# Generated by Django 5.1.3 on 2024-11-12 04:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offered_program', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('program_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='offered_program.programs')),
            ],
        ),
    ]
