# Generated by Django 5.1.3 on 2024-11-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissionPolicy', '0001_initial'),
        ('coursegroup', '0001_initial'),
        ('offered_program', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionpolicy',
            name='coursegroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursegroup.coursegroup'),
        ),
        migrations.AddField(
            model_name='admissionpolicy',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offered_program.programs'),
        ),
    ]
