# Generated by Django 5.1.3 on 2024-11-12 04:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_heading', models.CharField(max_length=255)),
                ('news_description', tinymce.models.HTMLField()),
                ('news_image', models.FileField(default=None, max_length=250, null=True, upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Graduation', 'Graduation'), ('General', 'General')], default='General', max_length=50)),
            ],
        ),
    ]
