# Generated by Django 5.1.3 on 2024-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='download/')),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('general', 'General'), ('timetable', 'TimeTable'), ('datesheet', 'DateSheet'), ('notification', 'Notification'), ('general_order', 'General Order')], default='general', max_length=20)),
            ],
        ),
    ]
