# Generated by Django 5.1.3 on 2024-11-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_remove_registeredstudent_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredstudent',
            old_name='username',
            new_name='Name',
        ),
    ]
