# Generated by Django 5.1.3 on 2024-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0003_rename_username_registeredstudent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstudent',
            name='Name',
            field=models.CharField(max_length=150),
        ),
    ]
