# Generated by Django 5.1.3 on 2024-11-12 04:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_up_desc', models.CharField(max_length=1000)),
                ('pop_up_link', tinymce.models.HTMLField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'In Active')], default='active', max_length=50)),
            ],
        ),
    ]
