# Generated by Django 5.1.3 on 2024-11-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PopUpData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupdata',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
